# Generated by Django 3.0.10 on 2021-06-11 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name_plural': 'Upload'},
        ),
    ]
